// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_y2wkhXmNmQS1BPM74NBEUA8qkbWkqXI',
    appId: '1:257359271472:web:33ff52e148199d07ed3ff5',
    messagingSenderId: '257359271472',
    projectId: 'trust-bridge-app-94bce',
    authDomain: 'trust-bridge-app-94bce.firebaseapp.com',
    storageBucket: 'trust-bridge-app-94bce.firebasestorage.app',
    databaseURL: "https://trust-bridge-app-94bce-default-rtdb.firebaseio.com/"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjeAu9lCcjT_8lmyjwEy2IxBR2tgzbB5o',
    appId: '1:257359271472:android:28a832e6b2a63f4aed3ff5',
    messagingSenderId: '257359271472',
    projectId: 'trust-bridge-app-94bce',
    storageBucket: 'trust-bridge-app-94bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASx5ce_1jykS76gq71JIJKo4uGZqNI9lk',
    appId: '1:257359271472:ios:65fce9604326af40ed3ff5',
    messagingSenderId: '257359271472',
    projectId: 'trust-bridge-app-94bce',
    storageBucket: 'trust-bridge-app-94bce.firebasestorage.app',
    iosBundleId: 'com.example.courseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASx5ce_1jykS76gq71JIJKo4uGZqNI9lk',
    appId: '1:257359271472:ios:65fce9604326af40ed3ff5',
    messagingSenderId: '257359271472',
    projectId: 'trust-bridge-app-94bce',
    storageBucket: 'trust-bridge-app-94bce.firebasestorage.app',
    iosBundleId: 'com.example.courseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_y2wkhXmNmQS1BPM74NBEUA8qkbWkqXI',
    appId: '1:257359271472:web:b3e4ad2d6e42cdc3ed3ff5',
    messagingSenderId: '257359271472',
    projectId: 'trust-bridge-app-94bce',
    authDomain: 'trust-bridge-app-94bce.firebaseapp.com',
    storageBucket: 'trust-bridge-app-94bce.firebasestorage.app',
  );
}
